#pragma once

enum class ERR_CODE : short
{
	/// IsOK = 1
	ISOK = 1,

	/// Initialize Log = 10 ~ 
	CONSOLE_LOGGER_LOAD_FAIL,
	CONFIG_LOAD_FAIL,
	WSASTART_FAIL,
	SOCKET_SET_FAIL,
	SOCKET_BIND_FAIL,
	SOCKET_LISTEN_FAIL,
	SOCKET_OPT_SET_FAIL,

	/// Network Log = 20 ~
	ACCEPT_WSAWOULDBLOCK = 20,
	ACCEPT_API_ERROR,
	CLIENT_2_SERVER_CONNECT_FAIL,
	MAX_CLIENT_CONNECT_COUNT,
	SELECT_FAIL,
	SELECT_TIMEOUT,
	EVENTSELECT_FAIL,
	ES_NO_EVENT,
	RECV_API_ERROR,
	RECV_REMOTE_CLOSE,
	RECV_BUFFER_OVER_MAXSIZE,
	RECV_NOT_CONNECTED,
	SEND_BUFFER_OVER_MAXSIZE,
	SEND_SIZE_ZERO,
};