#pragma once

enum class ObjectID : unsigned int
{
	///  MainScene
	SCENE_START = 100,
	SCENE_MAINMENU,
	SCENE_ENDING,

	/// InGameScene
	SCENE_INGAME_DESERT,
	SCENE_INGAME_FOREST,
	SCENE_INGAME_SEA,

	/// ChildScene
	CHILD_SCENE_MYTOWN_MAINMENU,
	CHILD_SCENE_DESERT_MAINMENU,
	CHILD_SCENE_SEA_MAINMENU,
	CHILD_SCENE_FOREST_MAINMENU,
	CHILD_SCENE_OPTION_MAINMENU,
	CHILD_SCENE_PAUSE_INGAME,
	CHILD_NEXT_SCENE_SLIDE_INGAMEMENU,

	CHILD_SCENE_FAIL_INGAME,
	CHILD_SCENE_CLEAR_INGAME,
	/// control
	BUTTON_PALY,
	BUTTON_INGAME_1,
	BUTTON_INGAME_2,
	BUTTON_INGAME_3,
	BUTTON_INGAME_4,
	BUTTON_INGAME_5,
	BUTTON_INGAME_6,
	BUTTON_INGAME_7,
	BUTTON_INGAME_8,

	BUTTON_SELECT_EASY,
	BUTTON_SELECT_NORMAL,
	BUTTON_SELECT_HARD,
	BUTTON_GAME_START,

	BUTTON_MENU_DESERT,
	BUTTON_MENU_SEA,
	BUTTON_MENU_FOREST,
	BUTTON_MENU_MYTOWN,
	BUTTON_OPTION,
	BUTTON_EXIT,
	BUTTON_MENU_EXIT,

	TEXTBOX_MENU_BESTSCORE,
	TEXTBOX_MENU_COMBO,
	TEXTBOX_MENU_KILL,
	TEXTBOX_MENU_RATE,
	TEXTBOX_MENU_MUSIC_NAME,
	TEXTBOX_MENU_MUSIC_COMPOSER,
	TEXTBOX_MENU_SPEED,
	TEXTBOX_MENU_MUSIC_BPM,
	TEXTBOX_OPTION_JUDGMENT,

	BUTTON_MENU_SELECT_SPEED_UP,
	BUTTON_MENU_SELECT_SPEED_DOWN,

	OPTION_SELECT_SOUND,
	OPTION_SELECT_GAME,

	SCROLL_BAR_BGSOUND,
	SCROLL_BAR_PLAYSOUND,
	SCROLL_BAR_EFFECTSOUND,

	MENU_CIRCLE_RANK,
	MENU_INFO_STARS,

	BUTTON_JUDGMENT_LEFTARROW,
	BUTTON_JUDGMENT_RIGHTARROW,

	PAUSE_SCENE_BUTTON_CONTINUE,
	PAUSE_SCENE_BUTTON_RESTART,
	PAUSE_SCENE_BUTTON_MUSIC_SELECT,

	OBJECT_MONSTER_RED = 400,
	OBJECT_MONSTER_GREEN,
	OBJECT_MONSTER_BLUE,
	OBJECT_PLAYER_FAIRY,

	SCROLL_CIRCLE,

	NONE
};

/// Todo : ResourceID 기반으로 리소스 불러올 것.
enum class ResourceID : unsigned int
{
	///  MainScene
	SCENE_START = 100,
	SCENE_MAINMENU,
	SCENE_ENDING,

	/// InGameScene
	SCENE_INGAME_DESERT,
	SCENE_INGAME_FOREST,
	SCENE_INGAME_SEA,

	/// ChildScene
	CHILD_SCENE_MYTOWN_MAINMENU,
	CHILD_SCENE_DESERT_MAINMENU,
	CHILD_SCENE_SEA_MAINMENU,
	CHILD_SCENE_FOREST_MAINMENU,
	CHILD_SCENE_OPTION_MAINMENU,
	CHILD_NEXT_SCENE_SLIDE_INGAMEMENU,

	CHILD_SCENE_FAIL_INGAME,
	CHILD_SCENE_CLEAR_INGAME,

	/// control
	BUTTON_PALY,
	BUTTON_INGAME_1,
	BUTTON_INGAME_2,
	BUTTON_INGAME_3,
	BUTTON_INGAME_4,
	BUTTON_INGAME_5,
	BUTTON_INGAME_6,
	BUTTON_INGAME_7,
	BUTTON_INGAME_8,

	BUTTON_SELECT_EASY,
	BUTTON_SELECT_NORMAL,
	BUTTON_SELECT_HARD,

	BUTTON_SELECT_EASY_LIGHT,
	BUTTON_SELECT_NORMAL_LIGHT,
	BUTTON_SELECT_HARD_LIGHT,

	BUTTON_START_EASY,
	BUTTON_START_NORMAL,
	BUTTON_START_HARD,

	BUTTON_NAME_TOWN,

	BUTTON_NAME_FOREST,
	BUTTON_NAME_DESERT,
	BUTTON_NAME_SEA,

	BUTTON_NAME_SELECT_FOREST,
	BUTTON_NAME_SELECT_DESERT,
	BUTTON_NAME_SELECT_SEA,

	ICON_FORSET_HIRIGHT,
	ICON_DESERT_HIRIGHT,
	ICON_SEA_HIRIGHT,

	TEXTBOX_MENU_BESTSCORE,
	TEXTBOX_MENU_COMBO,
	TEXTBOX_MENU_KILL,
	TEXTBOX_MENU_RATE,
	TEXTBOX_MENU_MUSIC_INFO_BG,
	TEXTBOX_MENU_SPEED,

	MENU_SELECT_SPEED_UP,
	MENU_SELECT_SPEED_DOWN,
	MENU_SELECT_STARTS,

	MENU_SELECT_RANK_A,
	MENU_SELECT_RANK_B,
	MENU_SELECT_RANK_C,
	MENU_SELECT_RANK_S,

	PLAY_SQUARE,
	PLAY_SQUARE_MISS,

	BUTTON_MENU_DESERT,
	BUTTON_MENU_SEA,
	BUTTON_MENU_FOREST,
	BUTTON_MENU_MYTOWN,
	BUTTON_OPTION,
	BUTTON_EXIT,
	BUTTON_MENU_EXIT,

	SETTING_WINDOW,
	SETTING_SOUND_TEXT,
	SETTING_SETTING_TEXT,
	BUTTON_OPTION_GAME,
	BUTTON_OPTION_GAMESELECT,
	BUTTON_OPTION_SOUND,
	BUTTON_OPTION_SOUNDSELECT,

	SCROLL_BAR,
	SCROLL_STONE,

	BUTTON_JUDGMENT_LEFTARROW,
	BUTTON_JUDGMENT_RIGHTARROW,

	PAUSE_SCENE,
	PAUSE_SCENE_BUTTON_CONTINUE,
	PAUSE_SCENE_BUTTON_RESTART,
	PAUSE_SCENE_BUTTON_MUSIC_SELECT,

	MONSTER_GREEN_EASY_WALK,
	MONSTER_GREEN_EASY_ATTACK,
	MONSTER_GREEN_EASY_DEATH,
	MONSTER_GREEN_NORMAL_WALK,
	MONSTER_GREEN_NORMAL_ATTACK,
	MONSTER_GREEN_NORMAL_DEATH,
	MONSTER_GREEN_HARD_WALK,
	MONSTER_GREEN_HARD_ATTACK,
	MONSTER_GREEN_HARD_DEATH,

	MONSTER_BLUE_EASY_WALK,
	MONSTER_BLUE_EASY_ATTACK,
	MONSTER_BLUE_EASY_DEATH,
	MONSTER_BLUE_NORMAL_WALK,
	MONSTER_BLUE_NORMAL_ATTACK,
	MONSTER_BLUE_NORMAL_DEATH,
	MONSTER_BLUE_HARD_WALK,
	MONSTER_BLUE_HARD_ATTACK,
	MONSTER_BLUE_HARD_DEATH,

	MONSTER_RED_EASY_WALK,
	MONSTER_RED_EASY_ATTACK,
	MONSTER_RED_EASY_DEATH,
	MONSTER_RED_NORMAL_WALK,
	MONSTER_RED_NORMAL_ATTACK,
	MONSTER_RED_NORMAL_DEATH,
	MONSTER_RED_HARD_WALK,
	MONSTER_RED_HARD_ATTACK,
	MONSTER_RED_HARD_DEATH,

	PLAY_SCORE_BOX,
	PLAY_ATTRIBUTE_BOX,

	PLAYER_HP_BAR_BODY,
	PLAYER_HP_BAR_HEAD,
	PLAYER_HP_BAR_TAIL,
	PLAYER_HP_BAR_COVER,

	PLAY_FEVER_BAR_HEAD,
	PLAY_FEVER_BAR_TAIL,
	PLAY_FEVER_BAR_BODY,
	PLAY_FEVER_BAR_COVER,

	PLAY_EFECT_GOOD,
	PLAY_EFECT_FEVER_GOOD,
	PLAY_EFECT_MISS,
	PLAY_EFECT_PREFECT,
	PLAY_EFECT_PREFECT_FEVER,

	/// combo number
	COMBO_NUMBER_NORMAL_0,
	COMBO_NUMBER_NORMAL_1,
	COMBO_NUMBER_NORMAL_2,
	COMBO_NUMBER_NORMAL_3,
	COMBO_NUMBER_NORMAL_4,
	COMBO_NUMBER_NORMAL_5,
	COMBO_NUMBER_NORMAL_6,
	COMBO_NUMBER_NORMAL_7,
	COMBO_NUMBER_NORMAL_8,
	COMBO_NUMBER_NORMAL_9,

	/// combo fever
	COMBO_NUMBER_FEVER_0,
	COMBO_NUMBER_FEVER_1,
	COMBO_NUMBER_FEVER_2,
	COMBO_NUMBER_FEVER_3,
	COMBO_NUMBER_FEVER_4,
	COMBO_NUMBER_FEVER_5,
	COMBO_NUMBER_FEVER_6,
	COMBO_NUMBER_FEVER_7,
	COMBO_NUMBER_FEVER_8,
	COMBO_NUMBER_FEVER_9,

	/// continue number
	CONTINUE_NUMBER_1,
	CONTINUE_NUMBER_2,
	CONTINUE_NUMBER_3,


	LODINGIMAGE,
	PAUSE_PLAN,

	MUSIC_COVER_1,
	MUSIC_COVER_2,
	MUSIC_COVER_3,

	/// effect
	//accack
	ATT_EFF_LEAF_1,
	ATT_EFF_LEAF_2,
	ATT_EFF_LEAF_3,
	ATT_EFF_FIRE,
	ATT_EFF_WATER,
	ATT_EFF_GRASS,
	ATT_EFF_SLIME_FIRE,
	ATT_EFF_SLIME_GLASS,
	ATT_EFF_SLIME_WATER,

	// square
	PLAY_EFFECT_MAGIC_CIRCLE,
	PLAY_EFFECT_MAGIC_CIRCLE_LIGHT,
	PLAY_EFFECT_MAGIC_CIRCLE_BLACK,
	PLAY_EFFECT_MAGIC_CIRCLE_ATT_LIGHT,

	PLAY_EFFECT_MAGIC_BAR,
	PLAY_EFFECT_MAGIC_BAR_LIGHT,

	PLAY_EFFECT_NUM_1,
	PLAY_EFFECT_NUM_2,
	PLAY_EFFECT_NUM_3,
	PLAY_EFFECT_NUM_4,
	PLAY_EFFECT_NUM_5,
	PLAY_EFFECT_NUM_6,
	PLAY_EFFECT_NUM_7,
	PLAY_EFFECT_NUM_8,
	PLAY_EFFECT_NUM_9,

	PLAY_EFFECT_NUM_1_LIGHT,
	PLAY_EFFECT_NUM_2_LIGHT,
	PLAY_EFFECT_NUM_3_LIGHT,
	PLAY_EFFECT_NUM_4_LIGHT,
	PLAY_EFFECT_NUM_5_LIGHT,
	PLAY_EFFECT_NUM_6_LIGHT,
	PLAY_EFFECT_NUM_7_LIGHT,
	PLAY_EFFECT_NUM_8_LIGHT,
	PLAY_EFFECT_NUM_9_LIGHT,

	PLAY_EFFECT_NUM_1_BLACK,
	PLAY_EFFECT_NUM_2_BLACK,
	PLAY_EFFECT_NUM_3_BLACK,
	PLAY_EFFECT_NUM_4_BLACK,
	PLAY_EFFECT_NUM_5_BLACK,
	PLAY_EFFECT_NUM_6_BLACK,
	PLAY_EFFECT_NUM_7_BLACK,
	PLAY_EFFECT_NUM_8_BLACK,
	PLAY_EFFECT_NUM_9_BLACK,

	PLAY_NOTE_GUIDE_CIRCLE,
	PLAY_NOTE_CLICK,
	PLAY_NOTE_BACKROUND,

	PLAY_UI_COMBO_TEXT,
	PLAY_UI_COMBO_FEVER,
	PLAY_UI_PROGRESS_BAR,

	// icon
	PLAY_HEAL_ICON,

	/// game end
	GAME_LOSE_BACK_GROUND,
	GAME_CLEAR_BACKGROUND,
	GAME_CLEAR_SCROLL,
	GAME_CLEAR_CHARACTER,

	MONSTER_SHADOW_SPRITE,
	MONSTER_SHADOW,

	PERPECT_,
	GOOD_,
	MISS_,

	RANK_S,
	RANK_A,
	RANK_B,
	RANK_C,

	OBJECT_PLAYER_ = 500,
	OBJECT_PLAYER_FAIRY_SHOT,
	DUMMY_NOTE,
	NONE
};

enum class SoundID : unsigned int
{
	INTROSPECT_PRE_WAVE = 1001,
	PLOT_TWIST_PRE_WAVE,
	PRECISION_STRIKE_PRE_WAVE,

	PLAYER_ATTACK_FIRE,
	PLAYER_ATTACK_WATER,
	PLAYER_ATTACK_GRASS,

	MONSTER_ATTACK_FIRE,
	MONSTER_ATTACK_WATER,
	MONSTER_ATTACK_GRASS,

	LOBBY_BACKGROUND,

	START_BACKGROUND,

	SFX_BUTTON,






	NONE = 2000
};

